In [1]:
import os

In [2]:
import pandas as pd


In [3]:
os.getcwd()

'd:\\Projects\\ML Projects\\ML_Project_01\\ml_project1\\notebook'

In [4]:
train_file_path = r"D:\Projects\ML Projects\ML_Project_01\ml_project1\housing\artifact\data_ingestion\2022-12-21-09-56-22\ingested_data\train\housing.csv"

In [85]:
df = pd.read_csv(train_file_path)

In [6]:
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -121.46     38.52                29.0       3873.0           797.0   
1    -117.23     33.09                 7.0       5320.0           855.0   
2    -119.04     35.37                44.0       1618.0           310.0   
3    -117.13     32.75                24.0       1877.0           519.0   
4    -118.70     34.28                27.0       3536.0           646.0   

   population  households  median_income  median_house_value ocean_proximity  
0      2237.0       706.0         2.1736             72100.0          INLAND  
1      2015.0       768.0         6.3373            279600.0      NEAR OCEAN  
2       667.0       300.0         2.8750             82700.0          INLAND  
3       898.0       483.0         2.2264            112500.0      NEAR OCEAN  
4      1837.0       580.0         4.4964            238300.0       <1H OCEAN

In [7]:
df.shape

(16512, 10)

In [8]:
X,y = df.drop(columns=["median_house_value"], axis = 1),df[['median_house_value']]

____
Diff between `df["median_house_value"]` Vs `df[["median_house_value"]]`

In [9]:
df["median_house_value"]

0         72100.0
1        279600.0
2         82700.0
3        112500.0
4        238300.0
           ...   
16507    268500.0
16508     90400.0
16509    140400.0
16510    258100.0
16511     62700.0
Name: median_house_value, Length: 16512, dtype: float64

In [10]:
df[["median_house_value"]]

median_house_value
0                 72100.0
1                279600.0
2                 82700.0
3                112500.0
4                238300.0
...                   ...
16507            268500.0
16508             90400.0
16509            140400.0
16510            258100.0
16511             62700.0

[16512 rows x 1 columns]

___

In [11]:
X.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -121.46     38.52                29.0       3873.0           797.0   
1    -117.23     33.09                 7.0       5320.0           855.0   
2    -119.04     35.37                44.0       1618.0           310.0   
3    -117.13     32.75                24.0       1877.0           519.0   
4    -118.70     34.28                27.0       3536.0           646.0   

   population  households  median_income ocean_proximity  
0      2237.0       706.0         2.1736          INLAND  
1      2015.0       768.0         6.3373      NEAR OCEAN  
2       667.0       300.0         2.8750          INLAND  
3       898.0       483.0         2.2264      NEAR OCEAN  
4      1837.0       580.0         4.4964       <1H OCEAN

In [12]:
y.head()

median_house_value
0             72100.0
1            279600.0
2             82700.0
3            112500.0
4            238300.0

In [13]:
X.shape

(16512, 9)

In [14]:
y.shape

(16512, 1)

In [15]:
X.isna().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        158
population              0
households              0
median_income           0
ocean_proximity         0
dtype: int64

In [16]:
from sklearn.impute import SimpleImputer

In [17]:
numerical_column = X.drop(columns=['ocean_proximity'],axis=1)

In [18]:
numerical_column.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -121.46     38.52                29.0       3873.0           797.0   
1    -117.23     33.09                 7.0       5320.0           855.0   
2    -119.04     35.37                44.0       1618.0           310.0   
3    -117.13     32.75                24.0       1877.0           519.0   
4    -118.70     34.28                27.0       3536.0           646.0   

   population  households  median_income  
0      2237.0       706.0         2.1736  
1      2015.0       768.0         6.3373  
2       667.0       300.0         2.8750  
3       898.0       483.0         2.2264  
4      1837.0       580.0         4.4964

In [19]:
simple_imputer = SimpleImputer(strategy="median")

In [20]:
simple_imputer.fit_transform(numerical_column)

array([[-1.2146e+02,  3.8520e+01,  2.9000e+01, ...,  2.2370e+03,
         7.0600e+02,  2.1736e+00],
       [-1.1723e+02,  3.3090e+01,  7.0000e+00, ...,  2.0150e+03,
         7.6800e+02,  6.3373e+00],
       [-1.1904e+02,  3.5370e+01,  4.4000e+01, ...,  6.6700e+02,
         3.0000e+02,  2.8750e+00],
       ...,
       [-1.2272e+02,  3.8440e+01,  4.8000e+01, ...,  4.5800e+02,
         1.7200e+02,  3.1797e+00],
       [-1.2270e+02,  3.8310e+01,  1.4000e+01, ...,  1.2080e+03,
         5.0100e+02,  4.1964e+00],
       [-1.2214e+02,  3.9970e+01,  2.7000e+01, ...,  6.2500e+02,
         1.9700e+02,  3.1319e+00]])

In [21]:
simple_imputer.transform(numerical_column)

In [22]:
simple_imputer.feature_names_in_

array(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income'],
      dtype=object)

In [23]:
simple_imputer.statistics_

array([-118.51   ,   34.26   ,   29.     , 2119.     ,  433.     ,
       1164.     ,  408.     ,    3.54155])

In [24]:
X.longitude

0       -121.46
1       -117.23
2       -119.04
3       -117.13
4       -118.70
          ...  
16507   -117.07
16508   -121.42
16509   -122.72
16510   -122.70
16511   -122.14
Name: longitude, Length: 16512, dtype: float64

In [25]:
X.longitude.median()

-118.51

In [26]:
X.latitude.median()

34.26

In [27]:
simple_imputer.statistics_

array([-118.51   ,   34.26   ,   29.     , 2119.     ,  433.     ,
       1164.     ,  408.     ,    3.54155])

In [28]:
simple_imputer.feature_names_in_

array(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income'],
      dtype=object)

In [29]:
X.ocean_proximity

0            INLAND
1        NEAR OCEAN
2            INLAND
3        NEAR OCEAN
4         <1H OCEAN
            ...    
16507     <1H OCEAN
16508        INLAND
16509     <1H OCEAN
16510     <1H OCEAN
16511        INLAND
Name: ocean_proximity, Length: 16512, dtype: object

In [30]:
X.ocean_proximity.value_counts()

<1H OCEAN     7277
INLAND        5262
NEAR OCEAN    2124
NEAR BAY      1847
ISLAND           2
Name: ocean_proximity, dtype: int64

In [31]:
cat_simple_imputer = SimpleImputer(strategy="most_frequent")

In [32]:
cat_simple_imputer.fit_transform(X[['ocean_proximity']])

array([['INLAND'],
       ['NEAR OCEAN'],
       ['INLAND'],
       ...,
       ['<1H OCEAN'],
       ['<1H OCEAN'],
       ['INLAND']], dtype=object)

In [33]:
cat_simple_imputer.feature_names_in_

array(['ocean_proximity'], dtype=object)

In [34]:
cat_simple_imputer.statistics_

array(['<1H OCEAN'], dtype=object)

___
Code for Custom fit(), transform() and fit_transform() generator

In [35]:
class FeatureGenerator:
    def __init__(self,strategy = "median") -> None:
        self.strategy = strategy

    def fit(self,X):
        self.feature_names_in_= X.columns
        self.statistics_ = []
        for i in self.feature_names_in_:
            self.statistics_.append(X[i].median())

    def transform(self,X:pd.DataFrame):
        for idx,i in enumerate(X.columns):
            X[i].fillna(self.statistics_[idx],inplace=True)
        return X

    def fit_transform(self,X):
        self.fit(X)
        return self.transform(X)

In [36]:
for idx,i in enumerate(X.columns):
    print(idx,i)

0 longitude
1 latitude
2 housing_median_age
3 total_rooms
4 total_bedrooms
5 population
6 households
7 median_income
8 ocean_proximity


In [37]:
obj =FeatureGenerator()

In [38]:
obj.fit(numerical_column)

In [39]:
obj.statistics_

[-118.51, 34.26, 29.0, 2119.0, 433.0, 1164.0, 408.0, 3.54155]

In [40]:
numerical_column.isna().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        158
population              0
households              0
median_income           0
dtype: int64

In [41]:
na_idx = numerical_column[numerical_column['total_bedrooms'].isna()].index

In [42]:
na_idx_list = [i for i in na_idx]

In [43]:
na_idx_list[:10]

[86, 373, 431, 528, 647, 681, 747, 888, 963, 1013]

In [44]:
res = obj.fit_transform(numerical_column)

In [45]:
res.loc[85:87,]

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
85    -118.17     34.05                35.0       1256.0           294.0   
86    -122.08     37.88                26.0       2947.0           433.0   
87    -118.22     33.98                36.0       1514.0           453.0   

    population  households  median_income  
85      2990.0       302.0         3.1528  
86       825.0       626.0         2.9330  
87      1496.0       448.0         2.1044

In [46]:
obj.statistics_

[-118.51, 34.26, 29.0, 2119.0, 433.0, 1164.0, 408.0, 3.54155]

In [47]:
res.iloc[na_idx_list]

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
86       -122.08     37.88                26.0       2947.0           433.0   
373      -117.87     33.73                45.0       2264.0           433.0   
431      -122.70     38.35                14.0       2313.0           433.0   
528      -118.23     34.13                48.0       1308.0           433.0   
647      -122.40     37.58                26.0       3281.0           433.0   
...          ...       ...                 ...          ...             ...   
15894    -121.95     38.03                 5.0       5526.0           433.0   
16109    -118.37     34.07                50.0       2519.0           433.0   
16129    -118.50     34.46                17.0      10267.0           433.0   
16152    -122.48     37.70                33.0       4492.0           433.0   
16370    -117.67     34.04                13.0       1543.0           433.0   

       population  households  median_income  
86          825.0       626.0         2.9330  
373        1970.0       499.0         3.4193  
431         954.0       397.0         3.7813  
528         835.0       294.0         4.2891  
647        1145.0       480.0         6.3580  
...           ...         ...            ...  
15894      3207.0      1012.0         4.0767  
16109      1117.0       516.0         4.3667  
16129      4956.0      1483.0         5.5061  
16152      3477.0      1537.0         3.0546  
16370       776.0       358.0         3.0598  

[158 rows x 8 columns]

In [48]:
obj.transform(numerical_column).loc[372:374,]

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
372    -117.96     33.81                35.0       1996.0           326.0   
373    -117.87     33.73                45.0       2264.0           433.0   
374    -118.13     33.86                45.0       1320.0           256.0   

     population  households  median_income  
372      1409.0       330.0         4.7738  
373      1970.0       499.0         3.4193  
374       645.0       256.0         4.4000

___
TransformerMixin

If you dont want to use custom `fit()`,`transform()` and `fit_transform()` then you can inherit `TransformerMixin` which has inbuild `fit()`,`transform()` and `fit_transform()` methods.

In [49]:
from sklearn.base import BaseEstimator, TransformerMixin

In [50]:
class FeatureGeneratorDirect(BaseEstimator,TransformerMixin):
    def __init__(self,strategy = "median") -> None:
        self.strategy = strategy

____


In [61]:
from sklearn.base import BaseEstimator, TransformerMixin
from housing.exception import HousingException
import sys
import numpy as np

In [70]:
COLUMN_TOTAL_ROOMS = "total_rooms"
COLUMN_POPULATION = "population"
COLUMN_HOUSEHOLDS = "households"
COLUMN_TOTAL_BEDROOM = "total_bedrooms"

In [77]:
class FeatureGenerator(BaseEstimator, TransformerMixin):
    def __init__(self, add_bedrooms_per_room = True,
                 total_rooms_ix = 3,
                 population_ix = 5,
                 households_ix = 6,
                 total_bedrooms_ix = 4,
                 columns = None):
    
        """
        FeatureGenerator Initialization
        add_bedrooms_per_room: bool
        total_rooms_ix: int index number of total rooms columns
        population_ix: int index number of total population columns
        households_ix: int index number of total households columns
        total_bedrooms_ix: int index number of total bedrooms columns
        """
        try:
            self.columns = columns
            if self.columns is not None:
                total_rooms_ix = self.columns.index(COLUMN_TOTAL_ROOMS)
                population_ix = self.columns.index(COLUMN_POPULATION)
                households_ix = self.columns.index(COLUMN_HOUSEHOLDS)
                total_bedrooms_ix = self.columns.index(COLUMN_TOTAL_BEDROOM)

            self.add_bedrooms_per_room = add_bedrooms_per_room
            self.total_rooms_ix = total_rooms_ix
            self.population_ix = population_ix
            self.households_ix = households_ix
            self.total_bedrooms_ix = total_bedrooms_ix
        except Exception as e:
            raise HousingException(e,sys) from e

    def fit(self, X, y=None):
        return self

    def transform(self, X, y=None):
        try:
            room_per_household = X[:, self.total_rooms_ix] / X[:, self.households_ix]
            population_per_household = X[:, self.population_ix] / X[:, self.households_ix]
            if self.add_bedrooms_per_room:
                bedroom_per_room = X[:, self.total_bedrooms_ix] / X[:, self.total_rooms_ix]

                generated_feature = np.c_[X,room_per_household,population_per_household,bedroom_per_room]
            else:
                generated_feature = np.c_[X,room_per_household,population_per_household]
            
            return generated_feature
        except Exception as e:
            raise HousingException(e,sys) from e                


In [63]:
arr1 = np.arange(1,10)
arr2 = np.arange(11,20)

In [64]:
print("arr1:", arr1 )
print("arr2:", arr2)

arr1: [1 2 3 4 5 6 7 8 9]
arr2: [11 12 13 14 15 16 17 18 19]


In [65]:
np.c_[arr1,arr2]

array([[ 1, 11],
       [ 2, 12],
       [ 3, 13],
       [ 4, 14],
       [ 5, 15],
       [ 6, 16],
       [ 7, 17],
       [ 8, 18],
       [ 9, 19]])

___

In [66]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler

In [78]:
num_pipeline = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy="median")),
    ('feature_generator',FeatureGenerator()),
    ('scaling',StandardScaler())
])

In [75]:
from sklearn.preprocessing import OneHotEncoder

In [88]:
cat_pipeline = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy="most_frequent")),
    ('encoder',OneHotEncoder()),
    ('scaling',StandardScaler(with_mean=False))  
])

In [79]:
numerical_column.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income'],
      dtype='object')

In [80]:
num_column_name = ['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income']

cat_column_name = ['ocean_proximity']

In [89]:
preprocessing = ColumnTransformer([
    ('num_pipeline',num_pipeline,num_column_name),
    ('cat_pipeline',cat_pipeline,cat_column_name)]
)

In [90]:
preprocessing.fit_transform(df)

array([[-0.94135046,  1.34743822,  0.02756357, ...,  0.        ,
         0.        ,  0.        ],
       [ 1.17178212, -1.19243966, -1.72201763, ...,  0.        ,
         0.        ,  2.9869105 ],
       [ 0.26758118, -0.1259716 ,  1.22045984, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [-1.5707942 ,  1.31001828,  1.53856552, ...,  0.        ,
         0.        ,  0.        ],
       [-1.56080303,  1.2492109 , -1.1653327 , ...,  0.        ,
         0.        ,  0.        ],
       [-1.28105026,  2.02567448, -0.13148926, ...,  0.        ,
         0.        ,  0.        ]])

In [91]:
test_file_path = r"D:\Projects\ML Projects\ML_Project_01\ml_project1\housing\artifact\data_ingestion\2022-12-21-09-56-22\ingested_data\test\housing.csv"

In [92]:
test_df = pd.read_csv(test_file_path)

In [93]:
test_df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -118.39     34.12                29.0       6447.0          1012.0   
1    -120.42     34.89                24.0       2020.0           307.0   
2    -118.45     34.25                36.0       1453.0           270.0   
3    -118.10     33.91                35.0       1653.0           325.0   
4    -117.07     32.77                38.0       3779.0           614.0   

   population  households  median_income  median_house_value ocean_proximity  
0      2184.0       960.0         8.2816            500001.0       <1H OCEAN  
1       855.0       283.0         5.0099            162500.0       <1H OCEAN  
2       808.0       275.0         4.3839            204600.0       <1H OCEAN  
3      1072.0       301.0         3.2708            159700.0       <1H OCEAN  
4      1495.0       614.0         4.3529            184000.0      NEAR OCEAN

In [94]:
preprocessing.transform(test_df)

array([[ 0.59229422, -0.71065803,  0.02756357, ...,  0.        ,
         0.        ,  0.        ],
       [-0.42180959, -0.35049119, -0.37006852, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.56232071, -0.64985064,  0.5842485 , ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [-0.07211862, -0.56097831,  1.14093342, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.83208232, -0.93985512,  0.10708999, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.50736927, -0.67791559,  0.5842485 , ...,  0.        ,
         0.        ,  0.        ]])

In [95]:
import dill

In [96]:
with open('preprocessing.pkl','wb') as prep_file:
    dill.dump(preprocessing,prep_file)

In [101]:
with open('preprocessing.pkl', 'rb') as file_obj:
    prep_loaded_obj = dill.load(file_obj)

In [102]:
prep_loaded_obj.transform(test_df)

array([[ 0.59229422, -0.71065803,  0.02756357, ...,  0.        ,
         0.        ,  0.        ],
       [-0.42180959, -0.35049119, -0.37006852, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.56232071, -0.64985064,  0.5842485 , ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [-0.07211862, -0.56097831,  1.14093342, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.83208232, -0.93985512,  0.10708999, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.50736927, -0.67791559,  0.5842485 , ...,  0.        ,
         0.        ,  0.        ]])